name: simple

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run:  make
    - name: simple
      run:  ./simple
    - name: make clean
      run:  make clean
